[package]
name = "intro-clock-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.45"
log = "0.4.14"
raw-window-handle = "0.3.3"
wgpu = "0.11.0"
winit = { version = "0.25.0", features = ["web-sys"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.9.0"
pollster = "0.2.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log = "0.2.0"
wasm-bindgen = "0.2.78"
web-sys =  { version = "0.3.55", features = [

]}
